[common]
    logOutPath = "./out/out.log"

[server]
    gRPCPort = 9093
    restPort = 9094

[crypto]
    # BTC
    btcAddress = "2Mv9oHtTi8xktaSk7icgBN3xTFwW7v9B7Fm" # Wallet address.
    btcTestnet = true

    # ETH
    # Ethereum network id
      # 1 - MAIN net
      # 2 - ROPSTEN net
      # 3 - RINKEBY net
      # 4 - KOVAN net
      # 5 - INFURANET net
    ethNetworkId = 3
    infuraToken = "1FXGefsSL6IqcH6Zj5Gc"

    # Contract
    crowdsaleAddress = "0x97187f845217b2d6892c1726db02bcdaaab6489e"
    ownerPrivateKey = "28e5d6796f472566f7e1fabc0ac277f1b39527505293831f63979c33f0c7665f"
    ownerAddress = "0xc851D654F07Bfc2DbFEa8C7661a1cfca53575E47" # Important! Must be associated with ownerPrivateKey.
    gasPrice = 5000000000 # Wei.
    gasLimit = 4700000

[services]
    btcServicePort = 8083

[database]
    [database.dev]
        host = "127.0.0.1"
        port = 5432
        name = "testuser"
        user = "testuser"
        password = "password"

    [database.prod]
        host = "127.0.0.1"
        port = 5432
        name = "prodDB"
        user = "prodUSER"
        password = "prodPassword"
