[common]
    logOutPath = "./out/out.log"

[server]
    tcpPort = 8080

[crypto]
    # BTC
    btcAddress = "1NS4gbx1G2D5rc9PnvVsPys12nKxGiQg72" # Wallet address.

    # ETH
    # Ethereum network id
      # 1 - MAIN net
      # 2 - ROPSTEN net
      # 3 - RINKEBY net
      # 4 - KOVAN net
      # 5 - INFURANET net
    ethNetworkId = 2
    infuraToken = "1FXGefsSL6IqcH6Zj5Gc"

    # Contract
    crowdsaleAddress = ""
    ownerPrivateKey = ""
    ownerAddress = "" # Important! Must be associated with ownerPrivateKey.
    gasPrice = 11000000000 # Wei.
    gasLimit = 7499000

[services]
    btcServicePort = 8082

[database]
    [database.dev]
        host = "127.0.0.1"
        port = 5432
        name = "testuser"
        user = "testuser"
        password = "password"

    [database.prod]
        host = "127.0.0.1"
        port = 5432
        name = "prodDB"
        user = "prodUSER"
        password = "prodPassword"
