[common]
    logOutPath = "./out/out.log"

[server]
    gRPCPort = 9092
    restPort = 9091

[crypto]
    # BTC
    btcAddress = "2Mv9oHtTi8xktaSk7icgBN3xTFwW7v9B7Fm" # Wallet address.
    btcTestnet = true

    # ETH
    # Ethereum network id
      # 1 - MAIN net
      # 2 - ROPSTEN net
      # 3 - RINKEBY net
      # 4 - KOVAN net
      # 5 - INFURANET net
    ethNetworkId = 2
    infuraToken = "1FXGefsSL6IqcH6Zj5Gc"

    # Contract
    crowdsaleAddress = "0xec4428f18AbD0E538aEde524A4dF6F78C6978251"
    ownerPrivateKey = "093afb31f3bff9edb790580c27a81040dce8a1fef0053a61f30313cd53686dad"
    ownerAddress = "0xcD628372B2429b8E079C235Ee6843F03f298041E" # Important! Must be associated with ownerPrivateKey.
    gasPrice = 5000000000 # Wei.
    gasLimit = 4700000

[services]
    btcServicePort = 8082

[database]
    [database.dev]
        host = "127.0.0.1"
        port = 5432
        name = "testuser"
        user = "testuser"
        password = "password"

    [database.prod]
        host = "127.0.0.1"
        port = 5432
        name = "prodDB"
        user = "prodUSER"
        password = "prodPassword"
