[common]
    logOutPath = "./out/out.log"
    storePath = "./out/store"

[server]
    tcpPort = 8083

[bitcoin]
    rpcHost = "89.111.20.200:8332" # TODO: Change to localhost
    user = "bitcoin"
    password = "local321"
    private_key = "cTTFf6E8zeHPdNSDPFS3VTQSYLTGARKD3vCp2tJV1CM2WeeeTAPt"
    testnet = true
