// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/buyer/buyer.proto

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	api/buyer/buyer.proto

It has these top-level messages:
	GetBTCWalletReq
	GetBTCWalletResp
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// GetBTCWallet
type GetBTCWalletReq struct {
	EthAddress string `protobuf:"bytes,1,opt,name=ethAddress" json:"ethAddress,omitempty"`
	BtcAddress string `protobuf:"bytes,2,opt,name=btcAddress" json:"btcAddress,omitempty"`
}

func (m *GetBTCWalletReq) Reset()                    { *m = GetBTCWalletReq{} }
func (m *GetBTCWalletReq) String() string            { return proto.CompactTextString(m) }
func (*GetBTCWalletReq) ProtoMessage()               {}
func (*GetBTCWalletReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetBTCWalletReq) GetEthAddress() string {
	if m != nil {
		return m.EthAddress
	}
	return ""
}

func (m *GetBTCWalletReq) GetBtcAddress() string {
	if m != nil {
		return m.BtcAddress
	}
	return ""
}

type GetBTCWalletResp struct {
	BtcAddress string `protobuf:"bytes,1,opt,name=btcAddress" json:"btcAddress,omitempty"`
}

func (m *GetBTCWalletResp) Reset()                    { *m = GetBTCWalletResp{} }
func (m *GetBTCWalletResp) String() string            { return proto.CompactTextString(m) }
func (*GetBTCWalletResp) ProtoMessage()               {}
func (*GetBTCWalletResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetBTCWalletResp) GetBtcAddress() string {
	if m != nil {
		return m.BtcAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*GetBTCWalletReq)(nil), "auth.GetBTCWalletReq")
	proto.RegisterType((*GetBTCWalletResp)(nil), "auth.GetBTCWalletResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Auth service

type AuthClient interface {
	// Get BTC wallet by ETH wallet
	GetBTCWallet(ctx context.Context, in *GetBTCWalletReq, opts ...grpc.CallOption) (*GetBTCWalletResp, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) GetBTCWallet(ctx context.Context, in *GetBTCWalletReq, opts ...grpc.CallOption) (*GetBTCWalletResp, error) {
	out := new(GetBTCWalletResp)
	err := grpc.Invoke(ctx, "/auth.Auth/GetBTCWallet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthServer interface {
	// Get BTC wallet by ETH wallet
	GetBTCWallet(context.Context, *GetBTCWalletReq) (*GetBTCWalletResp, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_GetBTCWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBTCWalletReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetBTCWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/GetBTCWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetBTCWallet(ctx, req.(*GetBTCWalletReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBTCWallet",
			Handler:    _Auth_GetBTCWallet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/buyer/buyer.proto",
}

func init() { proto.RegisterFile("api/buyer/buyer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0x2c, 0xc8, 0xd4,
	0x4f, 0x2a, 0xad, 0x4c, 0x2d, 0x82, 0x90, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x2c, 0x89,
	0xa5, 0x25, 0x19, 0x52, 0x32, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x20, 0x35, 0x89, 0x79,
	0x79, 0xf9, 0x25, 0x89, 0x25, 0x99, 0xf9, 0x79, 0xc5, 0x10, 0x35, 0x4a, 0x81, 0x5c, 0xfc, 0xee,
	0xa9, 0x25, 0x4e, 0x21, 0xce, 0xe1, 0x89, 0x39, 0x39, 0xa9, 0x25, 0x41, 0xa9, 0x85, 0x42, 0x72,
	0x5c, 0x5c, 0xa9, 0x25, 0x19, 0x8e, 0x29, 0x29, 0x45, 0xa9, 0xc5, 0xc5, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x9c, 0x41, 0x48, 0x22, 0x20, 0xf9, 0xa4, 0x92, 0x64, 0x98, 0x3c, 0x13, 0x44, 0x1e, 0x21,
	0xa2, 0x64, 0xc4, 0x25, 0x80, 0x6a, 0x64, 0x71, 0x01, 0x9a, 0x1e, 0x46, 0x74, 0x3d, 0x46, 0x49,
	0x5c, 0x2c, 0x8e, 0xa5, 0x25, 0x19, 0x42, 0x51, 0x5c, 0x3c, 0xc8, 0x7a, 0x85, 0x44, 0xf5, 0x40,
	0x7e, 0xd0, 0x43, 0x73, 0xa2, 0x94, 0x18, 0x36, 0xe1, 0xe2, 0x02, 0x25, 0xe9, 0xa6, 0xcb, 0x4f,
	0x26, 0x33, 0x89, 0x2a, 0x09, 0xe8, 0x97, 0x19, 0xea, 0xa7, 0x23, 0xc9, 0x5a, 0x31, 0x6a, 0x25,
	0xb1, 0x81, 0x7d, 0x6c, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x44, 0xbc, 0x2a, 0x41, 0x2e, 0x01,
	0x00, 0x00,
}
